services:
 postgres:
    image: postgres:16
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rohan123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: